version: '3.9'
name: faculty-hours-gateway
services:
  web:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ../:/app/
    ports:
      - "8000:8000"
    networks:
      - gateway_network
      - common_network
networks:
  gateway_network:
    driver: bridge
  common_network:
    external: true
